using QuickType;
using TodoApi.AppDataContext;
using TodoApi.Models;

namespace TodoApi.Services
{
    public class DbInitializer
    {
        public static async Task Initialize(TodoDbContext context)
        {
            context.Database.EnsureCreated();

            // Check if there are any todos already in the database
            if (context.Todos.Any())
            {
                return; // Database has been seeded
            }

            HttpClient client = new HttpClient();
            var response = await client.GetAsync("https://dummyjson.com/todos");
            var result = await response.Content.ReadFromJsonAsync<Welcome>();

            if (result?.Todos != null && result.Todos.Length > 0)
            {
                foreach (var todo in result.Todos)
                {
                    context.Todos.Add(new Todo
                    {
                        Id = Guid.NewGuid(),
                        Title = todo.Todo,
                        IsCompleted = todo.Completed,
                        DateCreated = DateTime.Now,
                        DateUpdated = DateTime.Now
                    });
                }
                context.SaveChanges();
            }
        }
    }
}

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public class Welcome
    {
        [JsonProperty("todos")]
        public TodoModel[] Todos { get; set; }

        [JsonProperty("total")]
        public long Total { get; set; }

        [JsonProperty("skip")]
        public long Skip { get; set; }

        [JsonProperty("limit")]
        public long Limit { get; set; }
    }

    public class TodoModel
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("todo")]
        public string Todo { get; set; }

        [JsonProperty("completed")]
        public bool Completed { get; set; }

        [JsonProperty("userId")]
        public long UserId { get; set; }
    }


}
